name: app_pragma_prueba
description: A new Flutter project.
#Flutter Version Usada : 3.19.6
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.7
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.jpeg"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo.jpeg
    - .env.dev
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Black.ttf
          weight: 900
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Light.ttf
          weight: 300
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Thin.ttf
          weight: 200
        - asset: assets/fonts/SF-Pro/SF-Pro-Text-Ultralight.ttf
          weight: 100
